/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudiPendahuluanRouteImport } from './routes/studi-pendahuluan'
import { Route as PeraturanRouteImport } from './routes/peraturan'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PelaksanaanRouteImport } from './routes/pelaksanaan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvaluasiRouteImport } from './routes/evaluasi'
import { Route as BeritaAcaraRouteImport } from './routes/berita-acara'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerencanaanDppTypeRouteImport } from './routes/perencanaan.$dppType'
import { Route as PerencanaanDppTypeVerifikasiRouteImport } from './routes/perencanaan.$dppType.verifikasi'
import { Route as PerencanaanDppTypeRiwayatRouteImport } from './routes/perencanaan.$dppType.riwayat'
import { Route as PerencanaanDppTypeRekomtekRouteImport } from './routes/perencanaan.$dppType.rekomtek'
import { Route as PerencanaanDppTypeRekapRouteImport } from './routes/perencanaan.$dppType.rekap'
import { Route as PerencanaanDppTypeLaporanRouteImport } from './routes/perencanaan.$dppType.laporan'
import { Route as PerencanaanDppTypeBuatUsulanRouteImport } from './routes/perencanaan.$dppType.buat-usulan'

const StudiPendahuluanRoute = StudiPendahuluanRouteImport.update({
  id: '/studi-pendahuluan',
  path: '/studi-pendahuluan',
  getParentRoute: () => rootRouteImport,
} as any)
const PeraturanRoute = PeraturanRouteImport.update({
  id: '/peraturan',
  path: '/peraturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PelaksanaanRoute = PelaksanaanRouteImport.update({
  id: '/pelaksanaan',
  path: '/pelaksanaan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluasiRoute = EvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaAcaraRoute = BeritaAcaraRouteImport.update({
  id: '/berita-acara',
  path: '/berita-acara',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerencanaanDppTypeRoute = PerencanaanDppTypeRouteImport.update({
  id: '/perencanaan/$dppType',
  path: '/perencanaan/$dppType',
  getParentRoute: () => rootRouteImport,
} as any)
const PerencanaanDppTypeVerifikasiRoute =
  PerencanaanDppTypeVerifikasiRouteImport.update({
    id: '/verifikasi',
    path: '/verifikasi',
    getParentRoute: () => PerencanaanDppTypeRoute,
  } as any)
const PerencanaanDppTypeRiwayatRoute =
  PerencanaanDppTypeRiwayatRouteImport.update({
    id: '/riwayat',
    path: '/riwayat',
    getParentRoute: () => PerencanaanDppTypeRoute,
  } as any)
const PerencanaanDppTypeRekomtekRoute =
  PerencanaanDppTypeRekomtekRouteImport.update({
    id: '/rekomtek',
    path: '/rekomtek',
    getParentRoute: () => PerencanaanDppTypeRoute,
  } as any)
const PerencanaanDppTypeRekapRoute = PerencanaanDppTypeRekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => PerencanaanDppTypeRoute,
} as any)
const PerencanaanDppTypeLaporanRoute =
  PerencanaanDppTypeLaporanRouteImport.update({
    id: '/laporan',
    path: '/laporan',
    getParentRoute: () => PerencanaanDppTypeRoute,
  } as any)
const PerencanaanDppTypeBuatUsulanRoute =
  PerencanaanDppTypeBuatUsulanRouteImport.update({
    id: '/buat-usulan',
    path: '/buat-usulan',
    getParentRoute: () => PerencanaanDppTypeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berita-acara': typeof BeritaAcaraRoute
  '/evaluasi': typeof EvaluasiRoute
  '/login': typeof LoginRoute
  '/pelaksanaan': typeof PelaksanaanRoute
  '/pengaturan': typeof PengaturanRoute
  '/peraturan': typeof PeraturanRoute
  '/studi-pendahuluan': typeof StudiPendahuluanRoute
  '/perencanaan/$dppType': typeof PerencanaanDppTypeRouteWithChildren
  '/perencanaan/$dppType/buat-usulan': typeof PerencanaanDppTypeBuatUsulanRoute
  '/perencanaan/$dppType/laporan': typeof PerencanaanDppTypeLaporanRoute
  '/perencanaan/$dppType/rekap': typeof PerencanaanDppTypeRekapRoute
  '/perencanaan/$dppType/rekomtek': typeof PerencanaanDppTypeRekomtekRoute
  '/perencanaan/$dppType/riwayat': typeof PerencanaanDppTypeRiwayatRoute
  '/perencanaan/$dppType/verifikasi': typeof PerencanaanDppTypeVerifikasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berita-acara': typeof BeritaAcaraRoute
  '/evaluasi': typeof EvaluasiRoute
  '/login': typeof LoginRoute
  '/pelaksanaan': typeof PelaksanaanRoute
  '/pengaturan': typeof PengaturanRoute
  '/peraturan': typeof PeraturanRoute
  '/studi-pendahuluan': typeof StudiPendahuluanRoute
  '/perencanaan/$dppType': typeof PerencanaanDppTypeRouteWithChildren
  '/perencanaan/$dppType/buat-usulan': typeof PerencanaanDppTypeBuatUsulanRoute
  '/perencanaan/$dppType/laporan': typeof PerencanaanDppTypeLaporanRoute
  '/perencanaan/$dppType/rekap': typeof PerencanaanDppTypeRekapRoute
  '/perencanaan/$dppType/rekomtek': typeof PerencanaanDppTypeRekomtekRoute
  '/perencanaan/$dppType/riwayat': typeof PerencanaanDppTypeRiwayatRoute
  '/perencanaan/$dppType/verifikasi': typeof PerencanaanDppTypeVerifikasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berita-acara': typeof BeritaAcaraRoute
  '/evaluasi': typeof EvaluasiRoute
  '/login': typeof LoginRoute
  '/pelaksanaan': typeof PelaksanaanRoute
  '/pengaturan': typeof PengaturanRoute
  '/peraturan': typeof PeraturanRoute
  '/studi-pendahuluan': typeof StudiPendahuluanRoute
  '/perencanaan/$dppType': typeof PerencanaanDppTypeRouteWithChildren
  '/perencanaan/$dppType/buat-usulan': typeof PerencanaanDppTypeBuatUsulanRoute
  '/perencanaan/$dppType/laporan': typeof PerencanaanDppTypeLaporanRoute
  '/perencanaan/$dppType/rekap': typeof PerencanaanDppTypeRekapRoute
  '/perencanaan/$dppType/rekomtek': typeof PerencanaanDppTypeRekomtekRoute
  '/perencanaan/$dppType/riwayat': typeof PerencanaanDppTypeRiwayatRoute
  '/perencanaan/$dppType/verifikasi': typeof PerencanaanDppTypeVerifikasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berita-acara'
    | '/evaluasi'
    | '/login'
    | '/pelaksanaan'
    | '/pengaturan'
    | '/peraturan'
    | '/studi-pendahuluan'
    | '/perencanaan/$dppType'
    | '/perencanaan/$dppType/buat-usulan'
    | '/perencanaan/$dppType/laporan'
    | '/perencanaan/$dppType/rekap'
    | '/perencanaan/$dppType/rekomtek'
    | '/perencanaan/$dppType/riwayat'
    | '/perencanaan/$dppType/verifikasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berita-acara'
    | '/evaluasi'
    | '/login'
    | '/pelaksanaan'
    | '/pengaturan'
    | '/peraturan'
    | '/studi-pendahuluan'
    | '/perencanaan/$dppType'
    | '/perencanaan/$dppType/buat-usulan'
    | '/perencanaan/$dppType/laporan'
    | '/perencanaan/$dppType/rekap'
    | '/perencanaan/$dppType/rekomtek'
    | '/perencanaan/$dppType/riwayat'
    | '/perencanaan/$dppType/verifikasi'
  id:
    | '__root__'
    | '/'
    | '/berita-acara'
    | '/evaluasi'
    | '/login'
    | '/pelaksanaan'
    | '/pengaturan'
    | '/peraturan'
    | '/studi-pendahuluan'
    | '/perencanaan/$dppType'
    | '/perencanaan/$dppType/buat-usulan'
    | '/perencanaan/$dppType/laporan'
    | '/perencanaan/$dppType/rekap'
    | '/perencanaan/$dppType/rekomtek'
    | '/perencanaan/$dppType/riwayat'
    | '/perencanaan/$dppType/verifikasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeritaAcaraRoute: typeof BeritaAcaraRoute
  EvaluasiRoute: typeof EvaluasiRoute
  LoginRoute: typeof LoginRoute
  PelaksanaanRoute: typeof PelaksanaanRoute
  PengaturanRoute: typeof PengaturanRoute
  PeraturanRoute: typeof PeraturanRoute
  StudiPendahuluanRoute: typeof StudiPendahuluanRoute
  PerencanaanDppTypeRoute: typeof PerencanaanDppTypeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studi-pendahuluan': {
      id: '/studi-pendahuluan'
      path: '/studi-pendahuluan'
      fullPath: '/studi-pendahuluan'
      preLoaderRoute: typeof StudiPendahuluanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peraturan': {
      id: '/peraturan'
      path: '/peraturan'
      fullPath: '/peraturan'
      preLoaderRoute: typeof PeraturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelaksanaan': {
      id: '/pelaksanaan'
      path: '/pelaksanaan'
      fullPath: '/pelaksanaan'
      preLoaderRoute: typeof PelaksanaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluasi': {
      id: '/evaluasi'
      path: '/evaluasi'
      fullPath: '/evaluasi'
      preLoaderRoute: typeof EvaluasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita-acara': {
      id: '/berita-acara'
      path: '/berita-acara'
      fullPath: '/berita-acara'
      preLoaderRoute: typeof BeritaAcaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perencanaan/$dppType': {
      id: '/perencanaan/$dppType'
      path: '/perencanaan/$dppType'
      fullPath: '/perencanaan/$dppType'
      preLoaderRoute: typeof PerencanaanDppTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perencanaan/$dppType/verifikasi': {
      id: '/perencanaan/$dppType/verifikasi'
      path: '/verifikasi'
      fullPath: '/perencanaan/$dppType/verifikasi'
      preLoaderRoute: typeof PerencanaanDppTypeVerifikasiRouteImport
      parentRoute: typeof PerencanaanDppTypeRoute
    }
    '/perencanaan/$dppType/riwayat': {
      id: '/perencanaan/$dppType/riwayat'
      path: '/riwayat'
      fullPath: '/perencanaan/$dppType/riwayat'
      preLoaderRoute: typeof PerencanaanDppTypeRiwayatRouteImport
      parentRoute: typeof PerencanaanDppTypeRoute
    }
    '/perencanaan/$dppType/rekomtek': {
      id: '/perencanaan/$dppType/rekomtek'
      path: '/rekomtek'
      fullPath: '/perencanaan/$dppType/rekomtek'
      preLoaderRoute: typeof PerencanaanDppTypeRekomtekRouteImport
      parentRoute: typeof PerencanaanDppTypeRoute
    }
    '/perencanaan/$dppType/rekap': {
      id: '/perencanaan/$dppType/rekap'
      path: '/rekap'
      fullPath: '/perencanaan/$dppType/rekap'
      preLoaderRoute: typeof PerencanaanDppTypeRekapRouteImport
      parentRoute: typeof PerencanaanDppTypeRoute
    }
    '/perencanaan/$dppType/laporan': {
      id: '/perencanaan/$dppType/laporan'
      path: '/laporan'
      fullPath: '/perencanaan/$dppType/laporan'
      preLoaderRoute: typeof PerencanaanDppTypeLaporanRouteImport
      parentRoute: typeof PerencanaanDppTypeRoute
    }
    '/perencanaan/$dppType/buat-usulan': {
      id: '/perencanaan/$dppType/buat-usulan'
      path: '/buat-usulan'
      fullPath: '/perencanaan/$dppType/buat-usulan'
      preLoaderRoute: typeof PerencanaanDppTypeBuatUsulanRouteImport
      parentRoute: typeof PerencanaanDppTypeRoute
    }
  }
}

interface PerencanaanDppTypeRouteChildren {
  PerencanaanDppTypeBuatUsulanRoute: typeof PerencanaanDppTypeBuatUsulanRoute
  PerencanaanDppTypeLaporanRoute: typeof PerencanaanDppTypeLaporanRoute
  PerencanaanDppTypeRekapRoute: typeof PerencanaanDppTypeRekapRoute
  PerencanaanDppTypeRekomtekRoute: typeof PerencanaanDppTypeRekomtekRoute
  PerencanaanDppTypeRiwayatRoute: typeof PerencanaanDppTypeRiwayatRoute
  PerencanaanDppTypeVerifikasiRoute: typeof PerencanaanDppTypeVerifikasiRoute
}

const PerencanaanDppTypeRouteChildren: PerencanaanDppTypeRouteChildren = {
  PerencanaanDppTypeBuatUsulanRoute: PerencanaanDppTypeBuatUsulanRoute,
  PerencanaanDppTypeLaporanRoute: PerencanaanDppTypeLaporanRoute,
  PerencanaanDppTypeRekapRoute: PerencanaanDppTypeRekapRoute,
  PerencanaanDppTypeRekomtekRoute: PerencanaanDppTypeRekomtekRoute,
  PerencanaanDppTypeRiwayatRoute: PerencanaanDppTypeRiwayatRoute,
  PerencanaanDppTypeVerifikasiRoute: PerencanaanDppTypeVerifikasiRoute,
}

const PerencanaanDppTypeRouteWithChildren =
  PerencanaanDppTypeRoute._addFileChildren(PerencanaanDppTypeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeritaAcaraRoute: BeritaAcaraRoute,
  EvaluasiRoute: EvaluasiRoute,
  LoginRoute: LoginRoute,
  PelaksanaanRoute: PelaksanaanRoute,
  PengaturanRoute: PengaturanRoute,
  PeraturanRoute: PeraturanRoute,
  StudiPendahuluanRoute: StudiPendahuluanRoute,
  PerencanaanDppTypeRoute: PerencanaanDppTypeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
